== Project Tittle

=== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan
secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan
sistem.

=== Team Involved

Berikut adalah nama-nama yang terlibat dalam pengembangan sistem
______________. Masing-masing sudah dilengkapi dengan alamat email yang
bisa dihubungi jika diperlukan.

[cols=",,",options="header",]
|===
|*Name* |*Role* |*Email*
| | |
|===

=== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang
dicantumkan harus menyesuaikan dengan kebutuhan.

<<system-name/system-url.adoc#, System Url>>

<<system-name/architecture.adoc#, Architecture>>

<<system-name/technology.adoc#, Technology>>

<<system-name/environment.adoc#, Environment>>

<<system-name/database.adoc#, Database>>

<<system-name/release-deployment.adoc#, Release and Deployment>>

<<system-name/adr-template/source_architecture_template.adoc#, Document ADR >>


=== Onboarding Information

<<system-name/devonboard.adoc#, Developer Onboarding>>

<<system-name/development.adoc#, Development>>

<<system-name/convention.adoc#, Naming Convention>>

=== Dokumentasi

Berisi dokumen penunjang untuk penggunaan sistem, berikut adalah dokumen
yang biasa dimasukkan di dalamnya. User Manual Dokumen Integrasi (jika
ada) Dokumen Maintenance (jika ada) Dokumen API (jika ada)
