== System Name

=== Overview

Berisi deskripsi, etimologi penamaan, dan fungsi sistem yang dijabarkan
secara singkat. Sekaligus memuat informasi tentang tujuan pengembangan
sistem.

=== Team Involved

Berikut adalah nama-nama yang terlibat dalam pengembangan sistem
______________. Masing-masing sudah dilengkapi dengan alamat email yang
bisa dihubungi jika diperlukan.


|===
| Name | Role | Email 
| | |
|===

=== Technical Information

Berisi informasi teknis tentang sistem, adapun informasi yang
dicantumkan harus menyesuaikan dengan kebutuhan.

<<system-name/system-url.adoc#, System Url System Name>>

<<system-name/architecture.adoc#, Architecture System Name>>

<<system-name/technology.adoc#, Technology System Name>>

<<system-name/environment.adoc#, Environment System Name>>

<<system-name/database.adoc#, Database System Name>>

<<system-name/release-deployment.adoc#, Release and Deployment System Name>>

<<system-name/adr-doc.adoc#, Document ADR  System Name>>


=== Onboarding Information

<<system-name/devonboard.adoc#, Developer Onboarding Sytem Name>>

<<system-name/development.adoc#, Development System name>>

<<system-name/convention.adoc#, Naming Convention System Name>>

=== Dokumentasi

Berisi dokumen penunjang untuk penggunaan sistem, berikut adalah dokumen
yang biasa dimasukkan di dalamnya :

- User Manual Dokumen Integrasi (jika
ada) 
- Dokumen Maintenance (jika ada) 
- Dokumen API (jika ada)
- Maintenance Document (jika ada)
- Release Note (jika ada)
- Flow and Wireframe (jika ada)
- Functional Specification (jika ada)
